export interface WebsiteType {
  id: string
  name: string
  description: string
  icon: string
  modules: string[]
  pages: { title: string; slug: string; label?: string }[]
  defaultTemplate?: string
  color?: string
}

export const WEBSITE_TYPES: WebsiteType[] = [
  {
    id: 'music', name: 'Music / FM', description: 'Music and FM station with songs, artists, albums, playlists and a player', icon: 'Music',
    modules: ['auth', 'music', 'songs', 'artists', 'albums', 'playlists', 'stations', 'player', 'search', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Music', slug: 'music', label: 'Music' },
      { title: 'Artists', slug: 'artists', label: 'Artists' },
      { title: 'Albums', slug: 'albums', label: 'Albums' },
      { title: 'Playlists', slug: 'playlists', label: 'Playlists' },
      { title: 'Stations', slug: 'stations', label: 'FM Stations' },
      { title: 'About', slug: 'about', label: 'About' },
      { title: 'Contact', slug: 'contact', label: 'Contact' },
    ],
    defaultTemplate: 'tpl-music', color: '#ec4899',
  },
  {
    id: 'erp', name: 'ERP', description: 'Modular ERP with employees, customers, vendors, inventory, sales, purchases and finance', icon: 'Database',
    modules: ['auth', 'employees', 'customers', 'vendors', 'inventory', 'sales', 'purchases', 'finance', 'reports', 'analytics'],
    pages: [
      { title: 'Dashboard', slug: 'dashboard', label: 'Dashboard' },
      { title: 'Employees', slug: 'employees', label: 'Employees' },
      { title: 'Customers', slug: 'customers', label: 'Customers' },
      { title: 'Vendors', slug: 'vendors', label: 'Vendors' },
      { title: 'Inventory', slug: 'inventory', label: 'Inventory' },
      { title: 'Sales', slug: 'sales', label: 'Sales' },
      { title: 'Purchases', slug: 'purchases', label: 'Purchases' },
      { title: 'Finance', slug: 'finance', label: 'Finance' },
      { title: 'Reports', slug: 'reports', label: 'Reports' },
    ],
    defaultTemplate: 'tpl-corporate', color: '#6366f1',
  },
  {
    id: 'event', name: 'Event Management', description: 'Event management with events, tickets, attendees, registration, venues and schedules', icon: 'CalendarDays',
    modules: ['auth', 'events', 'tickets', 'attendees', 'registration', 'venues', 'schedules', 'payments', 'reports', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Events', slug: 'events', label: 'Events' },
      { title: 'Schedule', slug: 'schedule', label: 'Schedule' },
      { title: 'Tickets', slug: 'tickets', label: 'Tickets' },
      { title: 'Venues', slug: 'venues', label: 'Venues' },
      { title: 'About', slug: 'about', label: 'About' },
      { title: 'Contact', slug: 'contact', label: 'Contact' },
    ],
    defaultTemplate: 'tpl-wedding', color: '#f59e0b',
  },
  {
    id: 'restaurant', name: 'Restaurant', description: 'Restaurant with menu, categories, food items, orders, customers, reservations and offers', icon: 'Utensils',
    modules: ['auth', 'restaurants', 'menu', 'food', 'orders', 'customers', 'reservations', 'offers', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Menu', slug: 'menu', label: 'Menu' },
      { title: 'Reservations', slug: 'reservations', label: 'Reservations' },
      { title: 'Offers', slug: 'offers', label: 'Offers' },
      { title: 'About', slug: 'about', label: 'About' },
      { title: 'Contact', slug: 'contact', label: 'Contact' },
    ],
    defaultTemplate: 'tpl-restaurant', color: '#f97316',
  },
  {
    id: 'billing', name: 'Billing Software', description: 'Billing software with customers, products, invoices, payments, taxes, discounts and reports', icon: 'Receipt',
    modules: ['auth', 'customers', 'invoices', 'payments', 'taxes', 'discounts', 'reports', 'analytics'],
    pages: [
      { title: 'Dashboard', slug: 'dashboard', label: 'Dashboard' },
      { title: 'Invoices', slug: 'invoices', label: 'Invoices' },
      { title: 'Payments', slug: 'payments', label: 'Payments' },
      { title: 'Customers', slug: 'customers', label: 'Customers' },
      { title: 'Products', slug: 'products', label: 'Products' },
      { title: 'Reports', slug: 'reports', label: 'Reports' },
      { title: 'Settings', slug: 'settings', label: 'Settings' },
    ],
    defaultTemplate: 'tpl-corporate', color: '#10b981',
  },
  {
    id: 'marketplace', name: 'E-commerce', description: 'Online store with products, cart, orders, customers and payments', icon: 'ShoppingCart',
    modules: ['auth', 'profiles', 'products', 'cart', 'orders', 'reviews', 'payments', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Shop', slug: 'shop', label: 'Shop' },
      { title: 'Product', slug: 'product', label: 'Product' },
      { title: 'Cart', slug: 'cart', label: 'Cart' },
      { title: 'Checkout', slug: 'checkout', label: 'Checkout' },
      { title: 'Orders', slug: 'orders', label: 'Orders' },
      { title: 'Account', slug: 'account', label: 'My Account' },
    ],
    defaultTemplate: 'tpl-ecommerce', color: '#10b981',
  },
  {
    id: 'hotel', name: 'Hotel', description: 'Hotel website with rooms, bookings, amenities and reservation management', icon: 'Hotel',
    modules: ['auth', 'rooms', 'bookings', 'amenities', 'reservations', 'payments', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Rooms', slug: 'rooms', label: 'Rooms' },
      { title: 'Booking', slug: 'booking', label: 'Book Now' },
      { title: 'Amenities', slug: 'amenities', label: 'Amenities' },
      { title: 'Gallery', slug: 'gallery', label: 'Gallery' },
      { title: 'About', slug: 'about', label: 'About' },
      { title: 'Contact', slug: 'contact', label: 'Contact' },
    ],
    defaultTemplate: 'tpl-hotel', color: '#3b82f6',
  },
  {
    id: 'education', name: 'Education', description: 'School and college website with courses, programs, events and admissions', icon: 'GraduationCap',
    modules: ['auth', 'courses', 'programs', 'students', 'faculty', 'events', 'admissions', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Programs', slug: 'programs', label: 'Programs' },
      { title: 'Admissions', slug: 'admissions', label: 'Admissions' },
      { title: 'Faculty', slug: 'faculty', label: 'Faculty' },
      { title: 'Events', slug: 'events', label: 'Events' },
      { title: 'About', slug: 'about', label: 'About' },
      { title: 'Contact', slug: 'contact', label: 'Contact' },
    ],
    defaultTemplate: 'tpl-school', color: '#8b5cf6',
  },
  {
    id: 'healthcare', name: 'Healthcare', description: 'Hospital and clinic website with departments, doctors, appointments and services', icon: 'Stethoscope',
    modules: ['auth', 'departments', 'doctors', 'appointments', 'patients', 'services', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Departments', slug: 'departments', label: 'Departments' },
      { title: 'Doctors', slug: 'doctors', label: 'Doctors' },
      { title: 'Appointments', slug: 'appointments', label: 'Book Appointment' },
      { title: 'Services', slug: 'services', label: 'Services' },
      { title: 'About', slug: 'about', label: 'About' },
      { title: 'Contact', slug: 'contact', label: 'Contact' },
    ],
    defaultTemplate: 'tpl-hospital', color: '#ef4444',
  },
  {
    id: 'business', name: 'Business', description: 'Professional business website', icon: 'Building',
    modules: ['auth', 'blog', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'About', slug: 'about', label: 'About' },
      { title: 'Services', slug: 'services', label: 'Services' },
      { title: 'Contact', slug: 'contact', label: 'Contact' },
    ],
    defaultTemplate: 'tpl-agency', color: '#6366f1',
  },
  {
    id: 'news', name: 'News', description: 'News website with articles and categories', icon: 'Newspaper',
    modules: ['auth', 'news', 'blog', 'comments', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'News', slug: 'news', label: 'News' },
      { title: 'Categories', slug: 'categories', label: 'Categories' },
      { title: 'About', slug: 'about', label: 'About' },
      { title: 'Contact', slug: 'contact', label: 'Contact' },
    ],
    defaultTemplate: 'tpl-blog', color: '#ef4444',
  },
  {
    id: 'saas', name: 'SaaS', description: 'Software-as-a-service product site', icon: 'Rocket',
    modules: ['auth', 'tools', 'pricing', 'subscriptions', 'billing', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Features', slug: 'features', label: 'Features' },
      { title: 'Pricing', slug: 'pricing', label: 'Pricing' },
      { title: 'Docs', slug: 'docs', label: 'Documentation' },
      { title: 'Blog', slug: 'blog', label: 'Blog' },
      { title: 'Dashboard', slug: 'dashboard', label: 'Dashboard' },
    ],
    defaultTemplate: 'tpl-saas', color: '#6366f1',
  },
  {
    id: 'portfolio', name: 'Portfolio', description: 'Creative portfolio showcase', icon: 'Palette',
    modules: ['auth', 'portfolio', 'blog', 'contact', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Work', slug: 'work', label: 'My Work' },
      { title: 'About', slug: 'about', label: 'About' },
      { title: 'Blog', slug: 'blog', label: 'Blog' },
      { title: 'Contact', slug: 'contact', label: 'Contact' },
    ],
    defaultTemplate: 'tpl-portfolio', color: '#14b8a8',
  },
  {
    id: 'services', name: 'Services', description: 'Service marketplace with bookings', icon: 'Wrench',
    modules: ['auth', 'profiles', 'services', 'providers', 'bookings', 'reviews', 'payments', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Services', slug: 'services', label: 'Services' },
      { title: 'Providers', slug: 'providers', label: 'Providers' },
      { title: 'Booking', slug: 'booking', label: 'Book Now' },
      { title: 'About', slug: 'about', label: 'About' },
      { title: 'Contact', slug: 'contact', label: 'Contact' },
    ],
    defaultTemplate: 'tpl-agency', color: '#3b82f6',
  },
  {
    id: 'jobs', name: 'Jobs', description: 'Job portal for employers and candidates', icon: 'Briefcase',
    modules: ['auth', 'employers', 'jobs', 'candidates', 'applications', 'resumes', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Jobs', slug: 'jobs', label: 'Jobs' },
      { title: 'Companies', slug: 'companies', label: 'Companies' },
      { title: 'Post a Job', slug: 'jobs/post', label: 'Post a Job' },
      { title: 'My Applications', slug: 'applications', label: 'My Applications' },
    ],
    defaultTemplate: 'tpl-corporate', color: '#8b5cf6',
  },
  {
    id: 'property', name: 'Property', description: 'Property listing platform', icon: 'Home',
    modules: ['auth', 'property', 'agents', 'listings', 'enquiries', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Listings', slug: 'listings', label: 'Listings' },
      { title: 'Search', slug: 'search', label: 'Search' },
      { title: 'Agents', slug: 'agents', label: 'Agents' },
      { title: 'Enquire', slug: 'enquire', label: 'Enquire' },
    ],
    defaultTemplate: 'tpl-realestate', color: '#f59e0b',
  },
  {
    id: 'grocery', name: 'Grocery', description: 'Grocery delivery and subscription platform', icon: 'ShoppingBasket',
    modules: ['auth', 'products', 'cart', 'orders', 'subscriptions', 'payments', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Shop', slug: 'shop', label: 'Shop' },
      { title: 'Cart', slug: 'cart', label: 'Cart' },
      { title: 'Checkout', slug: 'checkout', label: 'Checkout' },
      { title: 'My Orders', slug: 'orders', label: 'My Orders' },
    ],
    defaultTemplate: 'tpl-ecommerce', color: '#4f46e5',
  },
  {
    id: 'ai-tools', name: 'AI Tools', description: 'AI tool directory and marketplace', icon: 'Brain',
    modules: ['auth', 'tools', 'billing', 'subscriptions', 'ratings', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Tools', slug: 'tools', label: 'AI Tools' },
      { title: 'Pricing', slug: 'pricing', label: 'Pricing' },
      { title: 'Dashboard', slug: 'dashboard', label: 'Dashboard' },
    ],
    defaultTemplate: 'tpl-saas', color: '#8b5cf6',
  },
  {
    id: 'drive', name: 'File/Drive', description: 'File storage and sharing platform', icon: 'HardDrive',
    modules: ['auth', 'files', 'folders', 'sharing', 'starred', 'storage'],
    pages: [
      { title: 'Home', slug: 'home', label: 'My Drive' },
      { title: 'Shared', slug: 'shared', label: 'Shared' },
      { title: 'Starred', slug: 'starred', label: 'Starred' },
      { title: 'Recent', slug: 'recent', label: 'Recent' },
    ],
    defaultTemplate: 'tpl-personal', color: '#06b6d4',
  },
  {
    id: 'blog', name: 'Blog', description: 'Content blog with articles and newsletter', icon: 'PenTool',
    modules: ['auth', 'blog', 'comments', 'newsletter', 'analytics'],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'Blog', slug: 'blog', label: 'Blog' },
      { title: 'About', slug: 'about', label: 'About' },
      { title: 'Subscribe', slug: 'subscribe', label: 'Subscribe' },
      { title: 'Contact', slug: 'contact', label: 'Contact' },
    ],
    defaultTemplate: 'tpl-blog', color: '#ec4899',
  },
  {
    id: 'landing', name: 'Landing Page', description: 'Single-page landing for marketing', icon: 'MousePointer',
    modules: ['analytics'],
    pages: [{ title: 'Home', slug: 'home', label: 'Home' }],
    defaultTemplate: 'tpl-landing', color: '#6366f1',
  },
  {
    id: 'custom', name: 'Custom', description: 'Build from scratch with custom modules', icon: 'Settings',
    modules: [],
    pages: [
      { title: 'Home', slug: 'home', label: 'Home' },
      { title: 'About', slug: 'about', label: 'About' },
      { title: 'Contact', slug: 'contact', label: 'Contact' },
    ],
    defaultTemplate: undefined,
    color: '#6b7280',
  },
]

export interface ModuleDefinition {
  key: string
  name: string
  description: string
  icon: string
}

export const MODULE_DEFINITIONS: Record<string, ModuleDefinition> = {
  auth: { key: 'auth', name: 'Authentication', description: 'User login, registration, profiles', icon: 'User' },
  profiles: { key: 'profiles', name: 'User Profiles', description: 'Public user profiles', icon: 'Users' },
  music: { key: 'music', name: 'Music', description: 'Music library and player', icon: 'Music' },
  songs: { key: 'songs', name: 'Songs', description: 'Song catalog with metadata and categories', icon: 'Music2' },
  artists: { key: 'artists', name: 'Artists', description: 'Artist profiles and discography', icon: 'Mic' },
  albums: { key: 'albums', name: 'Albums', description: 'Album management', icon: 'Disc3' },
  playlists: { key: 'playlists', name: 'Playlists', description: 'Curated playlists and library', icon: 'ListMusic' },
  stations: { key: 'stations', name: 'FM Stations', description: 'Radio/FM station management', icon: 'Radio' },
  player: { key: 'player', name: 'Music Player', description: 'Audio player and mini player', icon: 'PlayCircle' },
  employees: { key: 'employees', name: 'Employees', description: 'Employee records and management', icon: 'Users' },
  customers: { key: 'customers', name: 'Customers', description: 'Customer database', icon: 'Contact' },
  vendors: { key: 'vendors', name: 'Vendors', description: 'Vendor and supplier management', icon: 'Truck' },
  inventory: { key: 'inventory', name: 'Inventory', description: 'Stock and inventory control', icon: 'Boxes' },
  sales: { key: 'sales', name: 'Sales', description: 'Sales orders and invoices', icon: 'TrendingUp' },
  purchases: { key: 'purchases', name: 'Purchases', description: 'Purchase orders and procurement', icon: 'ShoppingCart' },
  finance: { key: 'finance', name: 'Finance', description: 'Finance and accounting', icon: 'Wallet' },
  events: { key: 'events', name: 'Events', description: 'Event management', icon: 'CalendarDays' },
  tickets: { key: 'tickets', name: 'Tickets', description: 'Ticket sales and inventory', icon: 'Ticket' },
  attendees: { key: 'attendees', name: 'Attendees', description: 'Attendee management', icon: 'Users' },
  registration: { key: 'registration', name: 'Registration', description: 'Event registration forms', icon: 'ClipboardList' },
  venues: { key: 'venues', name: 'Venues', description: 'Venue management', icon: 'MapPin' },
  schedules: { key: 'schedules', name: 'Schedules', description: 'Event schedules and timetables', icon: 'CalendarClock' },
  restaurants: { key: 'restaurants', name: 'Restaurants', description: 'Restaurant profiles and menus', icon: 'Utensils' },
  menu: { key: 'menu', name: 'Menu', description: 'Menu item management', icon: 'Menu' },
  food: { key: 'food', name: 'Food Items', description: 'Food item catalog', icon: 'ChefHat' },
  reservations: { key: 'reservations', name: 'Reservations', description: 'Table reservations', icon: 'CalendarCheck' },
  offers: { key: 'offers', name: 'Offers', description: 'Promotions and offers', icon: 'Tag' },
  invoices: { key: 'invoices', name: 'Invoices', description: 'Invoice generation and tracking', icon: 'FileText' },
  payments: { key: 'payments', name: 'Payments', description: 'Stripe/Razorpay payment processing', icon: 'CreditCard' },
  taxes: { key: 'taxes', name: 'Taxes', description: 'Tax configuration and rates', icon: 'Percent' },
  discounts: { key: 'discounts', name: 'Discounts', description: 'Discount rules and coupons', icon: 'BadgePercent' },
  rooms: { key: 'rooms', name: 'Rooms', description: 'Hotel room management', icon: 'BedDouble' },
  bookings: { key: 'bookings', name: 'Bookings', description: 'Booking system', icon: 'Calendar' },
  amenities: { key: 'amenities', name: 'Amenities', description: 'Hotel amenities and facilities', icon: 'Sparkles' },
  courses: { key: 'courses', name: 'Courses', description: 'Course catalog', icon: 'BookOpen' },
  programs: { key: 'programs', name: 'Programs', description: 'Academic programs', icon: 'GraduationCap' },
  students: { key: 'students', name: 'Students', description: 'Student management', icon: 'Users' },
  faculty: { key: 'faculty', name: 'Faculty', description: 'Faculty and staff', icon: 'UserCheck' },
  admissions: { key: 'admissions', name: 'Admissions', description: 'Admission applications', icon: 'ClipboardCheck' },
  departments: { key: 'departments', name: 'Departments', description: 'Medical departments', icon: 'Building2' },
  doctors: { key: 'doctors', name: 'Doctors', description: 'Doctor profiles and schedules', icon: 'Stethoscope' },
  appointments: { key: 'appointments', name: 'Appointments', description: 'Appointment booking', icon: 'CalendarClock' },
  patients: { key: 'patients', name: 'Patients', description: 'Patient records', icon: 'Users' },
  services: { key: 'services', name: 'Services', description: 'Service listings and categories', icon: 'Wrench' },
  providers: { key: 'providers', name: 'Service Providers', description: 'Provider profiles and availability', icon: 'Users' },
  employers: { key: 'employers', name: 'Employers', description: 'Employer company profiles', icon: 'Building' },
  jobs: { key: 'jobs', name: 'Jobs', description: 'Job listings with filters', icon: 'Briefcase' },
  candidates: { key: 'candidates', name: 'Candidates', description: 'Candidate profiles and resumes', icon: 'User' },
  applications: { key: 'applications', name: 'Applications', description: 'Job applications tracking', icon: 'FileText' },
  resumes: { key: 'resumes', name: 'Resumes', description: 'Candidate resume management', icon: 'FileText' },
  property: { key: 'property', name: 'Property', description: 'Property listing management', icon: 'Home' },
  agents: { key: 'agents', name: 'Agents', description: 'Real estate agent profiles', icon: 'Users' },
  listings: { key: 'listings', name: 'Listings', description: 'Property listings', icon: 'Map' },
  enquiries: { key: 'enquiries', name: 'Enquiries', description: 'Property enquiry system', icon: 'Mail' },
  news: { key: 'news', name: 'News', description: 'News articles with categories and authors', icon: 'Newspaper' },
  blog: { key: 'blog', name: 'Blog', description: 'Content management with posts and comments', icon: 'PenTool' },
  comments: { key: 'comments', name: 'Comments', description: 'User comments on content', icon: 'MessageSquare' },
  products: { key: 'products', name: 'Products', description: 'Product catalog with categories', icon: 'Package' },
  cart: { key: 'cart', name: 'Cart', description: 'Shopping cart functionality', icon: 'ShoppingCart' },
  orders: { key: 'orders', name: 'Orders', description: 'Order management and tracking', icon: 'ClipboardList' },
  reviews: { key: 'reviews', name: 'Reviews & Ratings', description: 'Product and service reviews', icon: 'Star' },
  sellers: { key: 'sellers', name: 'Sellers', description: 'Multi-vendor seller management', icon: 'Store' },
  tools: { key: 'tools', name: 'AI Tools', description: 'AI tool directory', icon: 'Brain' },
  billing: { key: 'billing', name: 'Billing', description: 'Subscription and billing management', icon: 'CreditCard' },
  subscriptions: { key: 'subscriptions', name: 'Subscriptions', description: 'Recurring subscription plans', icon: 'RefreshCw' },
  files: { key: 'files', name: 'Files', description: 'File storage and management', icon: 'File' },
  folders: { key: 'folders', name: 'Folders', description: 'Folder organization for files', icon: 'Folder' },
  sharing: { key: 'sharing', name: 'Sharing', description: 'File sharing with permissions', icon: 'Share2' },
  starred: { key: 'starred', name: 'Starred', description: 'Starred/favorite files', icon: 'Star' },
  storage: { key: 'storage', name: 'Storage', description: 'Storage usage and quotas', icon: 'HardDrive' },
  analytics: { key: 'analytics', name: 'Analytics', description: 'Website analytics and insights', icon: 'BarChart3' },
  search: { key: 'search', name: 'Search', description: 'Site-wide search functionality', icon: 'Search' },
  newsletter: { key: 'newsletter', name: 'Newsletter', description: 'Email newsletter subscription', icon: 'Mail' },
  notifications: { key: 'notifications', name: 'Notifications', description: 'User notifications', icon: 'Bell' },
  ads: { key: 'ads', name: 'Ads', description: 'Advertisement management', icon: 'Megaphone' },
  seo: { key: 'seo', name: 'SEO', description: 'SEO optimization tools', icon: 'Globe' },
  contact: { key: 'contact', name: 'Contact', description: 'Contact form and page', icon: 'Mail' },
  pricing: { key: 'pricing', name: 'Pricing', description: 'Pricing page and plans', icon: 'CreditCard' },
  portfolio: { key: 'portfolio', name: 'Portfolio', description: 'Portfolio showcase items', icon: 'Palette' },
  reports: { key: 'reports', name: 'Reports', description: 'Reports and analytics dashboards', icon: 'BarChart3' },
}

export const getModuleDefinition = (key: string): ModuleDefinition | undefined => MODULE_DEFINITIONS[key]
export const getWebsiteType = (id: string): WebsiteType | undefined => WEBSITE_TYPES.find(t => t.id === id)